This notebook is only for calculating purposes of the matrix-vector multiplication $r^{t+1} = M \cdot r^{t}$.

In [8]:
import numpy as np

# a)

M = np.array([[1/3, 1/3, 1/3], [1/2, 0, 1/2], [0, 1/2, 1/2]]).transpose()
print(M)

r = np.array([[1/3, 1/3, 1/3]]).transpose()
r_plus = np.matmul(M,r)
print('r plus 1')
print(r_plus)

while(np.linalg.norm((r - r_plus), ord=1) > 1/12):
    print('Norm')
    print(np.linalg.norm((r - r_plus), ord=1))
    r = r_plus
    r_plus = np.matmul(M, r)
    print('r plus 1')
    print(r_plus)


print('Norm')
print(np.linalg.norm((r - r_plus), ord=1))

[[0.33333333 0.5        0.        ]
 [0.33333333 0.         0.5       ]
 [0.33333333 0.5        0.5       ]]
r plus 1
[[0.27777778]
 [0.27777778]
 [0.44444444]]
Norm
0.22222222222222215
r plus 1
[[0.23148148]
 [0.31481481]
 [0.4537037 ]]
Norm
0.09259259259259259
r plus 1
[[0.2345679 ]
 [0.30401235]
 [0.46141975]]
Norm
0.02160493827160484


In [9]:
# b)


vec = np.array([1/2, 2/3, 1])

print(vec/np.linalg.norm(vec, 1))

[0.23076923 0.30769231 0.46153846]


In [10]:
# c)

M = np.array([[1/3, 1/3, 1/3], [1/2, 0, 1/2], [0, 1/2, 1/2]]).transpose()*0.8
M_plus = np.full((3, 3), 1/3*0.2)
M = M + M_plus

print(M)

r = np.array([[1/3, 1/3, 1/3]]).transpose()
r_plus = np.matmul(M,r)
print('r plus 1')
print(r_plus)

while(np.linalg.norm((r - r_plus), ord=1) > 1/12):
    print('Norm')
    print(np.linalg.norm((r - r_plus), ord=1))
    r = r_plus
    r_plus = np.matmul(M, r)
    print('r plus 1')
    print(r_plus)


print('Norm')
print(np.linalg.norm((r - r_plus), ord=1))

[[0.33333333 0.46666667 0.06666667]
 [0.33333333 0.06666667 0.46666667]
 [0.33333333 0.46666667 0.46666667]]
r plus 1
[[0.28888889]
 [0.28888889]
 [0.42222222]]
Norm
0.1777777777777778
r plus 1
[[0.25925926]
 [0.31259259]
 [0.42814815]]
Norm
0.059259259259259234


In [11]:
# d)


vec = np.array([3/5, 5/7, 1])

print(vec/np.linalg.norm(vec, 1))

[0.25925926 0.30864198 0.43209877]
